type TextBlockKind = 'h1' | 'h2' | 'h3' | 'body';

interface TextBlock {
  kind: TextBlockKind;
  text: string;
}

const blockTags = new Set([
  'article',
  'aside',
  'blockquote',
  'div',
  'footer',
  'h1',
  'h2',
  'h3',
  'h4',
  'header',
  'li',
  'main',
  'ol',
  'p',
  'section',
  'table',
  'tbody',
  'td',
  'th',
  'thead',
  'tr',
  'ul',
]);

function normalizeText(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function blockKindFor(tagName: string): TextBlockKind {
  if (tagName === 'h1') return 'h1';
  if (tagName === 'h2') return 'h2';
  if (tagName === 'h3' || tagName === 'h4') return 'h3';
  return 'body';
}

function collectTextBlocks(root: ParentNode): TextBlock[] {
  const blocks: TextBlock[] = [];
  const elements = root.querySelectorAll(Array.from(blockTags).join(','));

  elements.forEach((element) => {
    const tagName = element.tagName.toLowerCase();
    const hasBlockChildren = Array.from(element.children).some((child) => {
      return blockTags.has(child.tagName.toLowerCase());
    });

    if (hasBlockChildren && tagName !== 'h1' && tagName !== 'h2' && tagName !== 'h3' && tagName !== 'h4') {
      return;
    }

    const text = normalizeText(element.textContent ?? '');
    if (!text) return;

    const last = blocks[blocks.length - 1];
    if (last?.text === text) return;

    blocks.push({
      kind: blockKindFor(tagName),
      text,
    });
  });

  return blocks;
}

function drawFooter(pdf: InstanceType<typeof import('jspdf').jsPDF>, pageWidth: number, pageHeight: number, pageNumber: number): void {
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(120, 130, 145);
  pdf.text(`Generated by AIVO Insights | Page ${pageNumber}`, pageWidth / 2, pageHeight - 24, { align: 'center' });
}

function blockStyle(kind: TextBlockKind): { fontSize: number; lineHeight: number; gapBefore: number; gapAfter: number; bold: boolean } {
  if (kind === 'h1') return { fontSize: 22, lineHeight: 29, gapBefore: 0, gapAfter: 12, bold: true };
  if (kind === 'h2') return { fontSize: 15, lineHeight: 21, gapBefore: 14, gapAfter: 8, bold: true };
  if (kind === 'h3') return { fontSize: 12, lineHeight: 17, gapBefore: 8, gapAfter: 5, bold: true };
  return { fontSize: 10.5, lineHeight: 15, gapBefore: 2, gapAfter: 7, bold: false };
}

export async function createPdfFromHtml(html: string): Promise<InstanceType<typeof import('jspdf').jsPDF>> {
  if (!html.trim()) {
    throw new Error('PDF source HTML was empty.');
  }

  const parsed = new DOMParser().parseFromString(html, 'text/html');
  const blocks = collectTextBlocks(parsed.body);

  if (blocks.length === 0) {
    throw new Error('PDF source did not contain readable text.');
  }

  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ unit: 'pt', format: 'a4', orientation: 'portrait' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const marginX = 48;
  const marginTop = 52;
  const marginBottom = 54;
  const maxWidth = pageWidth - marginX * 2;
  let pageNumber = 1;
  let y = marginTop;

  drawFooter(pdf, pageWidth, pageHeight, pageNumber);

  blocks.forEach((block) => {
    const style = blockStyle(block.kind);
    const lines = pdf.splitTextToSize(block.text, maxWidth) as string[];
    const blockHeight = lines.length * style.lineHeight + style.gapBefore + style.gapAfter;

    if (y + blockHeight > pageHeight - marginBottom) {
      pdf.addPage();
      pageNumber += 1;
      drawFooter(pdf, pageWidth, pageHeight, pageNumber);
      y = marginTop;
    }

    y += style.gapBefore;
    pdf.setFont('helvetica', style.bold ? 'bold' : 'normal');
    pdf.setFontSize(style.fontSize);
    pdf.setTextColor(block.kind === 'body' ? 31 : 15, block.kind === 'body' ? 41 : 23, block.kind === 'body' ? 55 : 42);

    lines.forEach((line) => {
      pdf.text(line, marginX, y);
      y += style.lineHeight;
    });

    y += style.gapAfter;
  });

  return pdf;
}

export async function downloadPdfFromHtml(html: string, filename: string): Promise<void> {
  const pdf = await createPdfFromHtml(html);
  pdf.save(filename);
}
